### ISSUE TITLE
SyntaxError: expected expression, got ':'

### ISSUE THREAD

**Issue by machal** [cdowdy/io-lazyload#3]
Hi, when I use `iolazy.js` fron `src/` folder, I'm getting this javascript error:

![image](https://user-images.githubusercontent.com/16641/35807708-d282ca90-0a83-11e8-9fef-cc336cd00c83.png)

Screen is from latest Firefox, but the same issue I can see in Chrome.

Using `dist/js/iolazy.min.js` everything is OK.

I prefer to use non-minified version - to create my own distrubution pack.

**Comment by cdowdy** [comment]
> I prefer to use non-minified version - to create my own distrubution pack.

Then you'll need to take into account all the things that are transpiled with babel.   

Specifically https://github.com/cdowdy/io-lazyload/blob/3ff535442ca26a09e1cc7224e922aaae3e5851ce/.babelrc#L10
