### ISSUE TITLE
Pass rootMargin as String

### ISSUE THREAD

**Issue by danieljb** [cdowdy/io-lazyload#5]
When using _IOlazy_ with `IntersectionObserver` Polyfill in Safari 11 the Polyfill’s `_parseRootMargin` method crashes with a TypeError `e.split is not a function. (In 'e.split(/\s+/)', 'e.split' is undefined)`.  
This is caused by _IOlazy_ [passing `rootMargin` as Array](https://github.com/cdowdy/io-lazyload/blob/master/src/js/iolazy.js#L36) which [can not work with the polyfill](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/IntersectionObserver/polyfill.js#L219-L220).

Please update _IOlazy_ class to pass `rootMargin` as String which is – as far as I can tell – [expected in the spec, too](https://w3c.github.io/IntersectionObserver/#dom-intersectionobserver-rootmargin).

**Comment by cdowdy** [comment]
thanks @danieljb I dunno why I overlooked that when I merged the PR. 

I'll push a fix here in a bit!

**Comment by danieljb** [comment]
Thanks for the super fast fix!
