### ISSUE TITLE
Placeholder image not updated with data-srcset image

### ISSUE THREAD

**Issue by theanatoki** [cdowdy/io-lazyload#6]
Firstly, thanks for taking the time to develop and share.

I am attempting to implement io-lazyload on a WordPress site. I can see that images are only downloaded by the browser as they come into view (as expected), however the image displayed to the user does not ever change from the low-res placeholder (in this case, an SVG). 

Test URL available @ https://staging.tabletop.melbourne/?test_io-lazyload

Cheers

**Comment by cdowdy** [comment]
hey @theanatoki is there a reason you closed this? I was going to look at it unless it's no longer an issue.  

If it's something that you came across that's a documentation problem, or anything else could ya let me know that way if it is a doc problem I can fix it or you can tell others who may have your issue how you fixed it.  

Thanks!

**Comment by theanatoki** [comment]
Hey @cdowdy 

Apologies, I must have clicked the wrong button. Issue reopened.

I've done some digging and I suspect there's a compatibility issue with jQuery Isotope and/or ImagesLoaded. I'm no JS wizard by any stretch of the imagination though...!

Cheers

**Comment by cdowdy** [comment]
hey @theanatoki I checked this out and it isn't an issue with the lazyload library. It another library you're using or your own JS/CSS that is conflicting.  see the GIF below.  


![opt-iolazy-scaled 2](https://user-images.githubusercontent.com/5969974/40983342-662236e6-68ad-11e8-9090-a504e969dafa.gif)
